// legacy-react/src/components/BottomNav.tsx
import React from 'react';
import { Home, Compass, HelpCircle, User } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { NavigateFn, Theme, ViewName } from '../types';

interface BottomNavProps {
  activeTab: string;
  navigateTo: NavigateFn;
  theme: Theme;
}

export default function BottomNav({ activeTab, navigateTo, theme }: BottomNavProps) {
  const isDark = theme === 'dark';
  const tabs: { id: ViewName; icon: LucideIcon; label: string }[] = [
    { id: 'home', icon: Home, label: 'Home' },
    { id: 'explore', icon: Compass, label: 'Explore' },
    { id: 'quiz-home', icon: HelpCircle, label: 'Quiz' },
    { id: 'profile', icon: User, label: 'Profil' }
  ];

  return (
    <div className={`backdrop-blur-2xl border shadow-2xl flex justify-between items-center p-2 rounded-[2.2rem] pointer-events-auto mx-auto max-w-[340px] transition-colors duration-300 ${
      isDark 
        ? 'bg-[#141720]/90 border-slate-800 shadow-black/80' 
        : 'bg-white/90 border-slate-200 shadow-slate-300/60'
    }`}>
      {tabs.map((tab) => {
        const isActive = activeTab === tab.id;
        return (
          <button
            key={tab.id}
            onClick={() => navigateTo(tab.id, tab.id)}
            className={`relative flex items-center justify-center h-12 px-4 rounded-[1.6rem] transition-all duration-300 ease-out active:scale-90 group ${
              isActive ? 'w-auto' : 'w-12'
            }`}
          >
            {isActive && (
              <div className="absolute inset-0 bg-blue-600 rounded-[1.6rem] shadow-lg shadow-blue-600/40 transition-all duration-300 ease-out"></div>
            )}
            
            <div className="relative z-10 flex items-center justify-center">
              <tab.icon 
                className={`transition-all duration-300 ${
                  isActive 
                    ? 'w-5 h-5 text-white stroke-[2.5]' 
                    : isDark ? 'w-5 h-5 text-slate-400 group-hover:text-slate-200 stroke-[2]' : 'w-5 h-5 text-slate-500 group-hover:text-slate-800 stroke-[2]'
                }`} 
              />
              {isActive && (
                <span className="ml-2 text-[13px] font-bold text-white tracking-wide whitespace-nowrap">
                  {tab.label}
                </span>
              )}
            </div>
          </button>
        );
      })}
    </div>
  );
}

// src/lib/components/BottomNav.svelte
<script lang="ts">
  import { Home, Compass, HelpCircle, User, Play } from '@lucide/svelte';
  import { page } from '$app/state';
  import { app } from '$lib/stores/app.svelte';

  let isDark = $derived(app.theme === 'dark');
  let currentPath = $derived(page.url.pathname);

  const tabs = [
    { id: '/', icon: Home, label: 'Home' },
    { id: '/explore', icon: Compass, label: 'Explore' },
    { id: '/quiz', icon: HelpCircle, label: 'Quiz' },
    { id: '/video', icon: Play, label: 'Video' },
    { id: '/profile', icon: User, label: 'Profil' }
  ];
</script>

<div
  class="border rounded flex justify-between items-center p-2 mx-auto max-w-xs pointer-events-auto {isDark
    ? 'bg-slate-900 border-slate-700'
    : 'bg-white border-slate-200'}"
>
  {#each tabs as tab}
    {@const isActive = currentPath === tab.id}
    <a
      href={tab.id}
      class="relative flex items-center justify-center h-12 px-4 rounded transition-all duration-200 active:scale-95 group {isActive ? 'w-auto' : 'w-12'}"
    >
      {#if isActive}
        <div class="absolute inset-0 bg-blue-600 rounded transition-all duration-200"></div>
      {/if}

      <div class="relative z-10 flex items-center justify-center">
        <tab.icon
          class="transition-all duration-200 {isActive
            ? 'w-5 h-5 text-white'
            : isDark
              ? 'w-5 h-5 text-slate-400 group-hover:text-slate-200'
              : 'w-5 h-5 text-slate-600 group-hover:text-slate-800'}"
        />
        {#if isActive}
          <span class="ml-2 text-xs font-bold text-white whitespace-nowrap">
            {tab.label}
          </span>
        {/if}
      </div>
    </a>
  {/each}
</div>
